// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfsMXQhCSV_gxp524c52h-nf2R6D4Q8D0',
    appId: '1:194829282437:web:331e66a701b35342f10dec',
    messagingSenderId: '194829282437',
    projectId: 'social-ca770',
    authDomain: 'social-ca770.firebaseapp.com',
    storageBucket: 'social-ca770.appspot.com',
    measurementId: 'G-T2141NS488',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5LPoijhUCOmODstKVw0hhJgs9M4_MxjU',
    appId: '1:194829282437:android:099566ba8fa80ec6f10dec',
    messagingSenderId: '194829282437',
    projectId: 'social-ca770',
    storageBucket: 'social-ca770.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk2IBOqit9DaSV7nENM4kjXimV-KngyMQ',
    appId: '1:194829282437:ios:e904ea7672ac1399f10dec',
    messagingSenderId: '194829282437',
    projectId: 'social-ca770',
    storageBucket: 'social-ca770.appspot.com',
    iosClientId: '194829282437-01jjni6fsloj5c4hg6ffkthss0ep353u.apps.googleusercontent.com',
    iosBundleId: 'com.example.social',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk2IBOqit9DaSV7nENM4kjXimV-KngyMQ',
    appId: '1:194829282437:ios:f435781e0aff7688f10dec',
    messagingSenderId: '194829282437',
    projectId: 'social-ca770',
    storageBucket: 'social-ca770.appspot.com',
    iosClientId: '194829282437-m3ccf8krcklm2u514g1t514cd0f96frf.apps.googleusercontent.com',
    iosBundleId: 'com.example.social.RunnerTests',
  );
}
